name: Build AprilTag

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release
    
    - name: Build
      run: cmake --build build --config Release
    
    - name: List output files
      run: dir build\Release\
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: windows-dll
        path: |
          build/Release/*.dll
          build/*.dll

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON
    
    - name: Build
      run: cmake --build build --config Release
    
    - name: List output files
      run: ls -la build/
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: linux-so
        path: build/*.so*