name: Build AprilTag for Unity

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:  # 允许手动触发

jobs:
  # Windows编译任务
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    
    - name: Configure CMake
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON
    
    - name: Build
      run: |
        cmake --build build --config Release
    
    - name: Upload Windows artifacts
      uses: actions/upload-artifact@v3
      with:
        name: windows-dll
        path: |
          build/Release/*.dll
          build/*.dll

  # Android编译任务
  build-android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25c
        add-to-path: true
    
    - name: Build for Android arm64-v8a
      run: |
        mkdir -p build-android-arm64
        cd build-android-arm64
        cmake .. -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
                 -DANDROID_ABI=arm64-v8a \
                 -DANDROID_PLATFORM=android-21 \
                 -DCMAKE_BUILD_TYPE=Release \
                 -DBUILD_SHARED_LIBS=ON
        cmake --build . --config Release
    
    - name: Upload Android artifacts
      uses: actions/upload-artifact@v3
      with:
        name: android-so
        path: build-android-arm64/*.so

  # iOS编译任务
  build-ios:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Build for iOS
      run: |
        mkdir -p build-ios
        cd build-ios
        cmake .. -DCMAKE_SYSTEM_NAME=iOS \
                 -DCMAKE_OSX_ARCHITECTURES=arm64 \
                 -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0 \
                 -DCMAKE_BUILD_TYPE=Release \
                 -DBUILD_SHARED_LIBS=OFF
        cmake --build . --config Release
    
    - name: Upload iOS artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ios-a
        path: build-ios/*.a

  # 打包所有平台的库
  package-all:
    needs: [build-windows, build-android, build-ios]
    runs-on: ubuntu-latest
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v3
    
    - name: Create Unity package structure
      run: |
        mkdir -p AprilTagUnity/Plugins/Windows/x86_64
        mkdir -p AprilTagUnity/Plugins/Android/libs/arm64-v8a
        mkdir -p AprilTagUnity/Plugins/iOS
        
        cp windows-dll/*.dll AprilTagUnity/Plugins/Windows/x86_64/
        cp android-so/*.so AprilTagUnity/Plugins/Android/libs/arm64-v8a/
        cp ios-a/*.a AprilTagUnity/Plugins/iOS/
        
        # 重命名文件以符合Unity命名规范
        mv AprilTagUnity/Plugins/Windows/x86_64/apriltag.dll AprilTagUnity/Plugins/Windows/x86_64/AprilTag.dll || true
        mv AprilTagUnity/Plugins/Android/libs/arm64-v8a/libapriltag.so AprilTagUnity/Plugins/Android/libs/arm64-v8a/libAprilTag.so || true
        mv AprilTagUnity/Plugins/iOS/libapriltag.a AprilTagUnity/Plugins/iOS/libAprilTag.a || true
    
    - name: Create release package
      run: |
        zip -r AprilTagUnity-AllPlatforms.zip AprilTagUnity/
    
    - name: Upload final package
      uses: actions/upload-artifact@v3
      with:
        name: AprilTagUnity-Package
        path: AprilTagUnity-AllPlatforms.zip