name: Build AprilTag

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    # Windows步骤保持不变...

  build-linux:
    runs-on: ubuntu-latest
    steps:
    # Linux步骤保持不变...

  build-android:
    runs-on: ubuntu-latest
    steps:
    # Android步骤保持不变...

  build-ios:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Build for iOS
      run: |
        mkdir -p build-ios
        cd build-ios
        cmake .. -DCMAKE_BUILD_TYPE=Release \
                 -DBUILD_SHARED_LIBS=OFF \
                 -DBUILD_EXAMPLES=OFF
        cmake --build . --config Release
    
    - name: List output files
      run: ls -la build-ios/
    
    - name: Upload iOS artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ios-a
        path: build-ios/*.a