name: Test iOS Build

on: workflow_dispatch

jobs:
  test-ios:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Check environment
      run: |
        echo "=== System Info ==="
        sw_vers
        echo "=== Xcode Info ==="
        xcodebuild -version
        echo "=== CMake Info ==="
        cmake --version
        echo "=== Available SDKs ==="
        xcodebuild -showsdks
    
    - name: Simple build test
      run: |
        mkdir -p build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        cmake --build . --config Release