name: Test Simple Build

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Test CMake
      run: |
        cmake --version
        ls -la
        
    - name: Configure
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release
      
    - name: Build
      run: cmake --build build --config Release